### ISSUE TITLE
Merge external repos into main repo

### ISSUE THREAD

**Issue by jsumners-nr** [newrelic/node-newrelic#2123]
### Description

There are a set of repos that provide instrumentation features within the `newrelic` agent. They are:

- [x] https://github.com/newrelic/node-newrelic-aws-sdk.git
- [x] https://github.com/newrelic/node-newrelic-koa.git
- [ ] https://github.com/newrelic/newrelic-node-nextjs.git
- [x] https://github.com/newrelic/node-newrelic-superagent.git

At some point in the past, it was decided these should be in their own repository. Presumably, the thinking was that clients who need fixes in the specific instrumentations they provide could update those modules without having to wait for a new release of `newrelic`. That may be true, but the reality is that it isn't worth the complications it brings. Namely:

1. There are circular dependencies between the external packages and `newrelic`. As an example the difficulty this causes see https://github.com/newrelic/node-newrelic/pull/2104. It was difficult to orchestrate because changes needed to be made in at least the `aws-sdk` package the required coordinating with a new release of `newrelic` merely to move development of the PR along. 
2. We cannot make internal changes to `newrelic` without impacting the releases of the external modules. As an example, https://github.com/newrelic/node-newrelic/pull/2038 resulted in a new version of both `newrelic` and `aws-sdk`. Folks updated `aws-sdk` without updating `newrelic` and found themselves in a broken state because `aws-sdk` couldn't find the code it needed.

To fix these issues, and make our development of `newrelic` easier and more robust, we need to migrate these modules into the main `newrelic` code base.

Ideally, we will keep the histories of those external repos by utilizing [`--allow-unrelated-histories`](https://stackoverflow.com/questions/54836572/how-exactly-does-git-pull-allow-unrelated-histories-work).

Note: https://github.com/newrelic/node-newrelic/blob/c32cb2739ece3adcf5bd42e646071b3f59e691ba/test/versioned-external/external-repos.js should be updated as repos are migrated.
